In [14]:
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
from bokeh.plotting import figure, ColumnDataSource
from bokeh.models.widgets import Dropdown
from bokeh.io import curdoc
from bokeh.layouts import column

from bokeh.models import BooleanFilter, CDSView, Select, Range1d, HoverTool
from bokeh.palettes import Category20
from bokeh.models.formatters import NumeralTickFormatter

# Read data
def get_symbol_df(symbol=None):
    df = pd.DataFrame(pd.read_csv("C:/Users/HP/Desktop/Forex_algo/EURUSD_daily.csv"))[-50:]
    df.reset_index(inplace=True)
    df["Date"] = pd.to_datetime(df["Date"])
    return df

# plot basic stock prices
def plot_stock_price(stock):
    p = figure(plot_width=W_PLOT, plot_height=H_PLOT, tools=TOOLS,
               title="Stock price", toolbar_location='above')

    inc = stock.data['Close'] > stock.data['Open']
    dec = stock.data['Open'] > stock.data['Close']
    view_inc = CDSView(source=stock, filters=[BooleanFilter(inc)])
    view_dec = CDSView(source=stock, filters=[BooleanFilter(dec)])

    p.segment(x0='index', x1='index', y0='Low', y1='High', color=RED, source=stock, view=view_inc)
    p.segment(x0='index', x1='index', y0='Low', y1='High', color=GREEN, source=stock, view=view_dec)

    p.vbar(x='index', width=VBAR_WIDTH, top='Open', bottom='Close', fill_color=BLUE, line_color=BLUE,
           source=stock,view=view_inc, name="price")
    p.vbar(x='index', width=VBAR_WIDTH, top='Open', bottom='Close', fill_color=RED, line_color=RED,
           source=stock,view=view_dec, name="price")

    p.legend.location = "top_left"
    p.legend.border_line_alpha = 0
    p.legend.background_fill_alpha = 0
    p.legend.click_policy = "mute"
    
    return p



# Define constants
W_PLOT = 1500
H_PLOT = 600
TOOLS = 'pan,wheel_zoom,reset'

VBAR_WIDTH = 0.2
RED = Category20[7][6]
GREEN = Category20[5][4]

BLUE = Category20[3][0]
BLUE_LIGHT = Category20[3][1]

ORANGE = Category20[3][2]
PURPLE = Category20[9][8]
BROWN = Category20[11][10]

stock = ColumnDataSource(
    data=dict(Date=[], Open=[], Close=[], High=[], Low=[],index=[]))
symbol = 'EURUSD'
df = get_symbol_df(symbol)
stock.data = stock.from_df(df)
elements = list()

# update_plot()
p_stock = plot_stock_price(stock)

elements.append(p_stock)

curdoc().add_root(column(elements))
curdoc().title = 'Bokeh stocks historical prices'

In [16]:
bokeh serve — show xxx.py

SyntaxError: invalid syntax (<ipython-input-16-22a1148159e1>, line 1)

In [15]:
df = pd.DataFrame(pd.read_csv("C:/Users/HP/Desktop/Forex_algo/EURUSD_daily.csv"))[-50:]
df

            Date    Open    High     Low   Close  Volume
4950  10/10/2002  0.9900  0.9926  0.9846  0.9860       0
4951   9/10/2002  0.9769  0.9912  0.9767  0.9901       0
4952   8/10/2002  0.9820  0.9843  0.9760  0.9770       0
4953   7/10/2002  0.9790  0.9830  0.9775  0.9819       0
4954   4/10/2002  0.9866  0.9885  0.9779  0.9794       0
4955   3/10/2002  0.9843  0.9908  0.9840  0.9865       0
4956   2/10/2002  0.9848  0.9861  0.9800  0.9846       0
4957   1/10/2002  0.9864  0.9892  0.9835  0.9847       0
4958   30/9/2002  0.9798  0.9898  0.9795  0.9861       0
4959   27/9/2002  0.9772  0.9801  0.9744  0.9793       0
4960   26/9/2002  0.9763  0.9809  0.9725  0.9773       0
4961   25/9/2002  0.9812  0.9851  0.9755  0.9761       0
4962   24/9/2002  0.9776  0.9836  0.9755  0.9811       0
4963   23/9/2002  0.9816  0.9860  0.9748  0.9775       0
4964   20/9/2002  0.9842  0.9875  0.9780  0.9803       0
4965   19/9/2002  0.9760  0.9859  0.9751  0.9845       0
4966   18/9/2002  0.9706  0.9793  0.9684  0.9761       0
4967   17/9/2002  0.9709  0.9713  0.9605  0.9708       0
4968   16/9/2002  0.9704  0.9726  0.9663  0.9709       0
4969   13/9/2002  0.9817  0.9837  0.9700  0.9722       0
4970   12/9/2002  0.9747  0.9816  0.9736  0.9810       0
4971   11/9/2002  0.9747  0.9768  0.9697  0.9746       0
4972   10/9/2002  0.9787  0.9840  0.9722  0.9747       0
4973    9/9/2002  0.9813  0.9828  0.9778  0.9785       0
4974    6/9/2002  0.9930  0.9954  0.9805  0.9808       0
4975    5/9/2002  0.9909  0.9989  0.9885  0.9930       0
4976    4/9/2002  0.9965  0.9975  0.9902  0.9910       0
4977    3/9/2002  0.9845  0.9973  0.9824  0.9962       0
4978    2/9/2002  0.9823  0.9855  0.9793  0.9846       0
4979   30/8/2002  0.9837  0.9863  0.9791  0.9816       0
4980   29/8/2002  0.9800  0.9884  0.9768  0.9835       0
4981   28/8/2002  0.9830  0.9836  0.9788  0.9800       0
4982   27/8/2002  0.9721  0.9838  0.9698  0.9830       0
4983   26/8/2002  0.9728  0.9743  0.9682  0.9721       0
4984   23/8/2002  0.9696  0.9730  0.9661  0.9718       0
4985   22/8/2002  0.9796  0.9813  0.9670  0.9700       0
4986   21/8/2002  0.9786  0.9845  0.9749  0.9795       0
4987   20/8/2002  0.9766  0.9807  0.9728  0.9789       0
4988   19/8/2002  0.9849  0.9870  0.9747  0.9767       0
4989   16/8/2002  0.9833  0.9865  0.9780  0.9837       0
4990   15/8/2002  0.9820  0.9848  0.9745  0.9835       0
4991   14/8/2002  0.9811  0.9893  0.9795  0.9819       0
4992   13/8/2002  0.9786  0.9828  0.9749  0.9812       0
4993   12/8/2002  0.9704  0.9799  0.9684  0.9787       0
4994    9/8/2002  0.9657  0.9739  0.9648  0.9703       0
4995    8/8/2002  0.9742  0.9772  0.9639  0.9657       0
4996    7/8/2002  0.9648  0.9763  0.9637  0.9742       0
4997    6/8/2002  0.9810  0.9819  0.9620  0.9648       0
4998    5/8/2002  0.9873  0.9878  0.9803  0.9809       0
4999    2/8/2002  0.9833  0.9917  0.9825  0.9865       0